version: 2

registries:
  npm-registry-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.CI_NPM_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    reviewers:
      - 'dryauk/ci'
    registries:
      - npm-registry-github
